name: Governance

on:
  pull_request:
    branches: [dev, preview, main]
  push:
    branches: [dev, preview, main]

permissions:
  contents: read

jobs:
  governance:
    uses: adafap/.github/.github/workflows/governance.yml@main

